version: '3'
volumes:
  yarn_cache:
  node_modules_blockchain:
services:
  blockchain:
    build:
      context: ./blockchain
      dockerfile: ./dev.dockerfile
    volumes:
      - yarn_cache:/yarn_cache
      - node_modules_blockchain:/app/node_modules
      - ./blockchain/src:/app/src:delegated
    ports:
      - 3000:3000
