version: '3'
volumes:
  yarn_cache:
  node_modules_node:
services:
  node:
    build:
      context: ./node
      dockerfile: ./dev.dockerfile
    environment:
      INSPECT_ENABLED: ${INSPECT_NODE-}
    volumes:
      - yarn_cache:/yarn_cache
      - node_modules_node:/app/node_modules
      - ./node/src:/app/src:delegated
    ports:
      - ${INSPECT_NODE-0}:9000
