version: '3'
volumes:
  yarn_cache:
  node_modules_blockchain:
services:
  blockchain:
    build:
      context: blockchain
      dockerfile: dev.dockerfile
    environment:
      INSPECT_ENABLED: ${INSPECT_NODE-}
    volumes:
      - yarn_cache:/yarn_cache
      - node_modules_blockchain:/app/node_modules
      - ./blockchain/src:/app/src:delegated
    ports:
      - ${INSPECT_NODE-0}:9000
