version: '3'
volumes:
  yarn_cache:
  mongodb_data:
  node_modules_blockchain:
  node_modules_web:
services:
  blockchain:
    build:
      context: ./blockchain
      dockerfile: ./dev.dockerfile
    environment:
      MONGO_CONNECTION: 'mongodb://mongodb:27017/blockchain'
    volumes:
      - yarn_cache:/yarn_cache
      - node_modules_blockchain:/app/node_modules
      - ./blockchain/src:/app/src:delegated
    ports:
      - 3000:3000
  web:
    build:
      context: ./web
      dockerfile: ./dev.dockerfile
    environment:
      REACT_APP_BACKEND_URL: 'http://localhost:3000'
    volumes:
      - yarn_cache:/yarn_cache
      - node_modules_web:/app/node_modules
      - ./web/src:/app/src:delegated
    ports:
      - 8080:3000
  mongodb:
    image: mongo:3.7-jessie
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
